flags:
  semigroups:
    bytestring-builder: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.0.2.0
- base-compat-0.9.1
- call-stack-0.1.0
- fail-4.9.0.0
- game-tree-0.1.0.0
- hspec-2.3.1
- hspec-core-2.3.1
- hspec-discover-2.3.1
- hspec-expectations-0.8.0
- scientific-0.3.4.9
- semigroups-0.18.2
- tagged-0.8.4
- unordered-containers-0.2.7.1
resolver: lts-4.2
